### ISSUE TITLE
Question regarding env

### ISSUE THREAD

**Issue by 996237275** [YuqiZhang-Buaa/Mamba2MIL#2]
Thank you for your work!

I have implemented my dataset on mambamil already and it works well. However, I got problem below while I using the same environment. 

Can you please share your environment and more details about you project?

Thanks.

```
Traceback (most recent call last):
  File "/isilon/datalake/cialab/scratch/cialab/yxguo/projects/breast_cancer/mambamil/main.py", line 251, in <module>
    results = main(args)
  File "/isilon/datalake/cialab/scratch/cialab/yxguo/projects/breast_cancer/mambamil/main.py", line 52, in main
    results, test_auc, val_auc, test_acc, val_acc  = train(datasets, i, args)
  File "/isilon/datalake/cialab/scratch/cialab/yxguo/projects/breast_cancer/mambamil/utils/core_utils.py", line 181, in train
    train_loop_func(epoch, model, train_loader, optimizer, args.n_classes, writer, loss_fn)
  File "/isilon/datalake/cialab/scratch/cialab/yxguo/projects/breast_cancer/mambamil/utils/core_utils.py", line 227, in train_loop
    logits, Y_prob, Y_hat, _, _ = model(data)
  File "/home/yoguo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yoguo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/isilon/datalake/cialab/scratch/cialab/yxguo/projects/breast_cancer/mambamil/models/Mamba2MIL.py", line 114, in forward
    h = layer[0](h)
  File "/home/yoguo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yoguo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/isilon/datalake/cialab/scratch/cialab/yxguo/projects/breast_cancer/mambamil/models/mamba_new/mamba_ssm/modules/mamba2.py", line 185, in forward
    out = mamba_split_conv1d_scan_combined(
  File "/isilon/datalake/cialab/scratch/cialab/yxguo/projects/breast_cancer/mambamil/models/mamba_new/mamba_ssm/ops/triton/ssd_combined.py", line 930, in mamba_split_conv1d_scan_combined
    return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate)
  File "/home/yoguo/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/yoguo/.local/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 113, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/isilon/datalake/cialab/scratch/cialab/yxguo/projects/breast_cancer/mambamil/models/mamba_new/mamba_ssm/ops/triton/ssd_combined.py", line 779, in forward
    causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"),
TypeError: causal_conv1d_fwd(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch.Tensor, arg1: torch.Tensor, arg2: Optional[torch.Tensor], arg3: Optional[torch.Tensor], arg4: bool) -> torch.Tensor

Invoked with: tensor([[[ 0.0474, -0.0002,  0.0200,  ...,  0.0169,  0.0070,  0.0286],
         [-0.0131, -0.0158, -0.0231,  ..., -0.0090,  0.0372,  0.0264],
         [-0.0087, -0.0112, -0.0040,  ..., -0.0024, -0.0088, -0.0223],
         ...,
         [-0.0428, -0.0340, -0.0251,  ..., -0.0890, -0.0807, -0.0271],
         [ 0.0523, -0.0060,  0.0646,  ...,  0.0159,  0.0157,  0.0653],
         [ 0.0492,  0.0445,  0.0477,  ...,  0.0248,  0.0481,  0.0490]]],
       device='cuda:0', requires_grad=True), tensor([[ 0.4339, -0.3071, -0.0542,  0.2720],
        [ 0.3423,  0.0496,  0.3143,  0.1576],
        [-0.2684,  0.1739, -0.4744, -0.0952],
        ...,
        [-0.4698, -0.0926, -0.3719,  0.4881],
        [ 0.4404,  0.0595,  0.1685, -0.2664],
        [ 0.3137,  0.0506, -0.2978, -0.4320]], device='cuda:0',
       grad_fn=<ViewBackward0>), Parameter containing:
tensor([ 0.3756, -0.0595,  0.2033,  ...,  0.3138,  0.4390,  0.3418],
       device='cuda:0', requires_grad=True), None, None, None, True
```

**Comment by YuqiZhang-Buaa** [comment]
I have added disclosure of environmental details. You can also contact me at the email address in the paper if you have any questions.
